Improve ATXConfig handling
jenkinsci/ecutest-plugin pull request #663
Opened 2024-02-21 14:58 UTC by ErikRehmTT

resolves #662

2024-02-27 14:02 UTC, ErikRehmTT commented on README.md
> +    def atx = newAtxServer atxName: 'test.guide', toolName: 'ecu.test',
then it will not work

2024-03-13 11:08 UTC, ErikRehmTT commented on src/main/java/de/tracetronic/jenkins/plugins/ecutest/report/atx/installation/ATXSecretSetting.java
> +     * @param name  the name
If you mean the two spaces between `name` and `the name` that this is the formatting to align all descriptions

2024-03-13 12:18 UTC, ErikRehmTT commented on src/main/java/de/tracetronic/jenkins/plugins/ecutest/report/atx/pipeline/ATXServer.java
> +        return installation.getConfig().getCustomSettingByName(settingName).orElse(null);
Now covered indirect in the `ATXNewServerStepIT` test

2024-03-13 12:31 UTC, ErikRehmTT commented on src/test/java/de/tracetronic/jenkins/plugins/ecutest/report/atx/installation/ATXConfigTest.java
> +        assertThat(((ATXCustomTextSetting)setting.get()).getValue(), is("bar"));
Not sure what you mean. The test is testing this function

2024-03-15 12:21 UTC, MartinGroscheTT requested changes

2024-03-15 12:21 UTC, MartinGroscheTT commented on src/main/resources/de/tracetronic/jenkins/plugins/ecutest/report/atx/pipeline/ATXNewServerStep/help_de.html
> -ATX.newServer(String atxName, String toolName, String fullServerURL, boolean uploadToServer, String authKey, String projectId) : ATXServer
this [should work anyway](https://github.com/jenkinsci/ecutest-plugin/blob/316b993ee7b7795e1527169531a855d972a7a590/src/main/java/de/tracetronic/jenkins/plugins/ecutest/report/atx/pipeline/ATXPipeline.java#L131)

2024-03-15 13:49 UTC, MartinGroscheTT approved these changes

2024-03-15 14:34 UTC, merged