Bump jenkins-core to 2.479.3 (#773)
jenkinsci/ecutest-plugin pull request #774
Opened 2024-12-19 10:14 UTC by ErikRehmTT

resolves #773

2024-12-19 12:38 UTC, ErikRehmTT commented
Blocked till Release of Jenkins 2.479.3 (08.01.) and rollout of maven 3.9.9 to ubuntu runners (10.01.)

2025-01-27 08:04 UTC, MartinGroscheTT requested changes

2025-01-27 08:04 UTC, MartinGroscheTT commented on config/allowed_licenses.json
Found dead links:
- ❌  https://github.com/freemansoft/jacob-project/blob/B-1_10/jacob/License.TXT → Status: 404
- ❌  https://svn.apache.org/repos/asf/commons/proper/discovery/tags/DISCOVERY_0_5_RC2/LICENSE → Status: 404

2025-01-27 16:11 UTC, ErikRehmTT commented on config/allowed_licenses.json
Updated them

2025-01-28 14:51 UTC, MartinGroscheTT approved these changes

2025-01-28 15:25 UTC, merged